#!/usr/bin/env python3
"""Integrate the reviewed August 2026 RERC site-improvement source packet."""

from __future__ import annotations

import json
from pathlib import Path

from catalog_maintenance import export_catalog


ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "data.js"
CASES = ROOT / "case_studies.js"
PREFIX = "window.RERC_CATALOG = "
CASE_PREFIX = "window.RERC_CASE_STUDIES="
CHECKED = "2026-08-10"
NATIONAL = "Nationwide and U.S. territories"


def funding(item_id, title, organization, status, geography, eligible, stage, tags,
            support, amount, match, deadline, summary, url):
    return {
        "item_id": item_id,
        "item_type": "Funding",
        "title": title,
        "organization": organization,
        "status": status,
        "last_checked": CHECKED,
        "geography": geography,
        "eligible_users": eligible,
        "project_stage": stage,
        "topic_tags": tags,
        "support_type": support,
        "amount_or_cost": amount,
        "match_or_cost": match,
        "deadline_or_availability": deadline,
        "summary": summary,
        "why_it_matters": summary,
        "source_url": url,
    }


def resource(item_id, title, organization, support, summary, url, geography=NATIONAL):
    return {
        "item_id": item_id,
        "item_type": "Resource",
        "title": title,
        "organization": organization,
        "status": "Available when checked",
        "last_checked": CHECKED,
        "geography": geography,
        "eligible_users": "Rural communities; local and Tribal governments; nonprofits; community partners",
        "project_stage": "Mixed",
        "topic_tags": "rural development; planning; eligibility; technical assistance",
        "support_type": support,
        "amount_or_cost": "Free public resource",
        "match_or_cost": "None",
        "deadline_or_availability": "Available online",
        "summary": summary,
        "why_it_matters": summary,
        "source_url": url,
    }


USDA = "USDA Rural Development"
NEW_ITEMS = [
    funding("RERC-FND-USDA-001", "Single Family Housing Guaranteed Loan Program", USDA, "Open when checked", NATIONAL,
            "Approved lenders serving low- and moderate-income rural homebuyers", "Implementation",
            "housing; homeownership; rural development", "Loan guarantee", "Up to 100% financing for qualified borrowers", "Program rules apply",
            "Applications are accepted through approved lenders on an ongoing basis from October 1 through September 30.",
            "Helps qualified rural households buy, build, improve, or relocate a primary home through approved lenders.",
            "https://www.rd.usda.gov/programs-services/single-family-housing-programs/single-family-housing-guaranteed-loan-program"),
    funding("RERC-FND-USDA-002", "Single Family Housing Repair Loans and Grants", USDA, "Open when checked", NATIONAL,
            "Very-low-income rural homeowners; grants are limited to eligible homeowners age 62 or older", "Implementation",
            "housing; home repair; accessibility; health and safety", "Loan and grant", "Loans up to $40,000; grants generally up to $10,000", "No match stated",
            "Applications are accepted through local Rural Development offices year-round.",
            "Pays for repairs, modernization, accessibility work, and removal of health and safety hazards in eligible rural homes.",
            "https://www.rd.usda.gov/programs-services/single-family-housing-programs/single-family-housing-repair-loans-grants"),
    funding("RERC-FND-USDA-003", "Rural Housing Site Loans", USDA, "Open when checked", NATIONAL,
            "Public and private nonprofits; federally recognized Tribes", "Planning",
            "housing; site development; infrastructure; self-help housing", "Loan", "Varies by eligible site-development project", "Repayment required",
            "Applications are accepted through local Rural Development offices on an ongoing basis.",
            "Finances the purchase and development of housing sites for low- and moderate-income rural households.",
            "https://www.rd.usda.gov/programs-services/single-family-housing-programs/rural-housing-site-loans"),
    funding("RERC-FND-USDA-004", "Housing Preservation Grants", USDA, "Cycle closed", NATIONAL,
            "State and local governments; nonprofits; federally recognized Tribes", "Implementation",
            "housing; rehabilitation; accessibility; rural development", "Grant", "Varies by funding notice", "See current NOFO",
            "Applications will be accepted after USDA publishes a new funding notice.",
            "Supports repair and rehabilitation of housing for low- and very-low-income rural residents.",
            "https://www.rd.usda.gov/programs-services/single-family-housing-programs/housing-preservation-grants"),
    funding("RERC-FND-USDA-005", "Multifamily Housing Direct Loans", USDA, "Cycle closed", NATIONAL,
            "Qualified public, nonprofit, Tribal, cooperative, and private applicants that cannot obtain suitable commercial credit", "Construction",
            "housing; rental housing; construction; rehabilitation", "Direct loan", "Competitive financing; amount varies", "Repayment required",
            "Applications will be accepted after USDA publishes a new funding notice.",
            "Finances affordable rental housing for low-income, elderly, and disabled rural residents.",
            "https://www.rd.usda.gov/programs-services/multifamily-housing-programs/multifamily-housing-direct-loans"),
    funding("RERC-FND-USDA-006", "Multifamily Housing Loan Guarantees", USDA, "Open when checked", NATIONAL,
            "Approved lenders financing eligible rural multifamily housing borrowers", "Construction",
            "housing; rental housing; construction; rehabilitation", "Loan guarantee", "Varies by approved loan", "Borrower and lender terms apply",
            "Applications are accepted from approved lenders; confirm current availability with USDA.",
            "Helps private lenders finance affordable rental housing in eligible rural areas.",
            "https://www.rd.usda.gov/programs-services/multifamily-housing-programs/multifamily-housing-loan-guarantees"),
    funding("RERC-FND-USDA-007", "Multifamily Preservation and Revitalization Program", USDA, "Cycle closed", NATIONAL,
            "Owners or purchasers of eligible USDA-financed rural rental and farm labor housing", "Implementation",
            "housing; preservation; rehabilitation; affordability", "Loan, grant, and debt restructuring", "Varies by funding notice", "See current NOFO",
            "Applications will be accepted after USDA publishes a new funding notice.",
            "Preserves and improves existing USDA-financed rural rental and off-farm labor housing.",
            "https://www.rd.usda.gov/programs-services/multifamily-housing-programs/multifamily-preservation-and-revitalization-mpr"),
    funding("RERC-FND-USDA-008", "Multifamily Nonprofit Transfer Technical Assistance Grants", USDA, "Cycle closed", NATIONAL,
            "Nonprofits; public housing authorities; Tribal housing nonprofits; Tribally designated housing entities", "Planning",
            "housing; preservation; technical assistance; property transfer", "Grant", "Competitive; amount varies", "No match stated",
            "Applications will be accepted after USDA publishes a new funding notice.",
            "Funds technical help needed to transfer eligible USDA multifamily properties to nonprofit or public ownership.",
            "https://www.rd.usda.gov/programs-services/multifamily-housing-programs/multifamily-housing-non-profit-transfer-technical-assistance-grants"),
    funding("RERC-FND-USDA-009", "Multifamily Housing Rental Assistance Program", USDA, "Ongoing", NATIONAL,
            "Owners of eligible USDA-financed rural rental or farm labor housing serving qualifying tenants", "Implementation",
            "housing; rental assistance; affordability", "Rental assistance", "Payments vary by eligible tenant and property", "Program rules apply",
            "Ongoing for eligible USDA-financed properties; contact the regional Multifamily Housing office.",
            "Provides rental assistance payments to owners on behalf of eligible low-income tenants.",
            "https://www.rd.usda.gov/programs-services/multifamily-housing-programs/multifamily-housing-rental-assistance"),
    funding("RERC-FND-USDA-010", "On-Farm Labor Housing Loans", USDA, "Open when checked", NATIONAL,
            "Farm owners; family farm partnerships and corporations; associations of farmers", "Construction",
            "housing; farm labor; construction; rehabilitation", "Direct loan", "Up to 100% of allowable development cost", "Repayment required",
            "Applications are accepted first-come, first-served until funds are depleted.",
            "Finances construction or rehabilitation of affordable housing for domestic, migrant, and seasonal farmworkers.",
            "https://www.rd.usda.gov/programs-services/multifamily-housing-programs/farm-labor-housing-loans"),
    funding("RERC-FND-USDA-011", "Off-Farm Labor Housing Direct Loans and Grants", USDA, "Cycle closed", NATIONAL,
            "Nonprofits; Tribes; community organizations; state and local governments; eligible partnerships", "Construction",
            "housing; farm labor; construction; rehabilitation", "Loan and grant", "Varies by funding notice", "Grants may cover up to 90% when eligible",
            "Applications will be accepted after USDA publishes a new funding notice.",
            "Supports affordable housing for year-round, migrant, and seasonal domestic farmworkers.",
            "https://www.rd.usda.gov/programs-services/multifamily-housing-programs/farm-labor-housing-direct-loans-grants"),
    funding("RERC-FND-USDA-012", "Farm Labor Housing Technical Assistance Grants", USDA, "Cycle closed", NATIONAL,
            "Qualified nonprofits providing technical assistance to farm labor housing applicants", "Planning",
            "housing; farm labor; technical assistance; applications", "Grant", "Varies by funding notice", "See current NOFO",
            "Applications will be accepted after USDA publishes a new funding notice.",
            "Funds technical assistance that helps eligible organizations prepare farm labor housing loan and grant applications.",
            "https://www.rd.usda.gov/programs-services/multifamily-housing-programs/farm-labor-housing-technical-assistance-grants"),
    funding("RERC-FND-USDA-013", "Community Facilities Direct Loan, Grant, and Guaranteed Loan Programs", USDA, "Open when checked", NATIONAL,
            "Public bodies; community nonprofits; federally recognized Tribes; approved lenders", "Mixed",
            "community facilities; public services; health; safety; local food", "Loan, grant, and loan guarantee", "Varies; grant share depends on need and community size", "Varies",
            "Direct applications and lender applications are accepted on an ongoing basis from October 1 through September 30.",
            "Funds essential rural facilities such as community centers, public safety buildings, clinics, libraries, and local food facilities.",
            "https://www.rd.usda.gov/programs-services/community-facilities/community-facilities-direct-loan-grant-program"),
    funding("RERC-FND-USDA-014", "Rural Community Development Initiative Grants", USDA, "Cycle closed", NATIONAL,
            "Public bodies; nonprofits; qualified private organizations; federally recognized Tribes", "Planning",
            "capacity building; housing; community facilities; economic development", "Grant", "$50,000 to $500,000 in recent guidance", "Dollar-for-dollar cash match",
            "Annual competitive cycle; next deadline will follow a new funding notice.",
            "Funds training and technical assistance for rural housing, facilities, and economic development organizations.",
            "https://www.rd.usda.gov/programs-services/community-facilities/rural-community-development-initiative-grants"),
    funding("RERC-FND-USDA-015", "Tribal College Initiative Grants", USDA, "Cycle closed", NATIONAL,
            "Eligible 1994 Land Grant Institutions and Tribal Colleges", "Construction",
            "Tribal communities; education; facilities; equipment", "Grant", "Up to $250,000 per eligible institution", "At least 5%",
            "Applications will be accepted after USDA publishes a new funding notice.",
            "Supports capital improvements, equipment, and essential community facilities at Tribal Colleges.",
            "https://www.rd.usda.gov/programs-services/community-facilities/tribal-college-initiative-grants"),
    funding("RERC-FND-USDA-016", "Electric Infrastructure Loan and Loan Guarantee Program", USDA, "Open when checked", NATIONAL,
            "Utilities, cooperatives, public bodies, Tribes, nonprofits, and eligible companies serving rural areas", "Construction",
            "electric infrastructure; energy efficiency; renewable energy; utilities", "Loan and loan guarantee", "Varies by approved project", "Repayment required",
            "Applications are accepted on an ongoing basis from October 1 through September 30.",
            "Finances rural electric distribution, transmission, generation, efficiency, and renewable-energy improvements.",
            "https://www.rd.usda.gov/programs-services/electric-programs/electric-infrastructure-loan-loan-guarantee-program"),
    funding("RERC-FND-USDA-017", "Community Connect Grants", USDA, "Cycle closed", NATIONAL,
            "State and local governments; Tribes; nonprofits; cooperatives; eligible businesses and other legal entities", "Construction",
            "broadband; digital access; community facilities; economic development", "Grant", "See current NOFO", "At least 15% nonfederal match",
            "The FY2026 application deadline was June 29, 2026; monitor the program page for the next cycle.",
            "Supports broadband service and community connectivity in rural areas where adequate service does not exist.",
            "https://www.rd.usda.gov/programs-services/telecommunications-programs/community-connect-grants"),
    funding("RERC-FND-USDA-018", "Distance Learning and Telemedicine Grants", USDA, "Paused", NATIONAL,
            "Public bodies; Tribes; nonprofits; eligible businesses and groups that provide education or health care", "Implementation",
            "telehealth; distance learning; broadband; equipment", "Grant", "$50,000 to $750,000 in FY2026 guidance", "At least 15% nonfederal match",
            "USDA states that applications are not currently being accepted because of funding constraints.",
            "Funds telecommunications equipment and related support for rural education and health care.",
            "https://www.rd.usda.gov/programs-services/telecommunications-programs/distance-learning-telemedicine-grants"),
    funding("RERC-FND-USDA-019", "ReConnect Loan and Grant Program", USDA, "Cycle closed", NATIONAL,
            "Eligible rural broadband providers, governments, Tribes, cooperatives, nonprofits, and businesses", "Construction",
            "broadband; digital access; rural infrastructure", "Loan and grant", "Varies by funding round", "Varies by funding category",
            "No application window was open when checked; monitor the official ReConnect page.",
            "Supports broadband deployment in rural areas that lack sufficient access to high-speed internet.",
            "https://www.usda.gov/reconnect"),
    funding("RERC-FND-USDA-020", "Rural Broadband Loans and Loan Guarantees", USDA, "Paused", NATIONAL,
            "Eligible corporations, cooperatives, nonprofits, governments, and Tribal organizations", "Construction",
            "broadband; telecommunications; rural infrastructure", "Loan", "Varies by approved project", "Repayment required",
            "USDA states that applications are not currently being accepted because of funding constraints.",
            "Finances construction, improvement, or acquisition of rural broadband facilities and equipment.",
            "https://www.rd.usda.gov/programs-services/telecommunications-programs/rural-broadband-loans-loangrant-combinations-and-loan-guarantees"),
    funding("RERC-FND-USDA-021", "Telecommunications Infrastructure Loans and Loan Guarantees", USDA, "Open when checked", NATIONAL,
            "Governments; Tribes; nonprofits; cooperatives; eligible telecommunications businesses", "Construction",
            "telecommunications; broadband; infrastructure", "Loan and loan guarantee", "Varies by approved project", "Repayment required",
            "Applications are accepted on an ongoing basis from October 1 through September 30.",
            "Finances construction, maintenance, improvement, and expansion of rural telephone and broadband service.",
            "https://www.rd.usda.gov/programs-services/telecommunications-programs/telecommunications-infrastructure-loans-loan-guarantees"),
    funding("RERC-FND-USDA-022", "Circuit Rider Technical Assistance for Rural Water Systems", USDA, "Open when checked", NATIONAL,
            "Rural water systems requesting operational, financial, or managerial assistance", "Mixed",
            "water systems; technical assistance; operations; management", "Technical assistance", "No cost stated", "None",
            "Available year-round; systems request help through a state rural water association or Rural Development office.",
            "Provides hands-on help for rural water systems facing operational, financial, or management problems.",
            "https://www.rd.usda.gov/programs-services/water-environmental-programs/circuit-rider-program-technical-assistance-rural-water-systems"),
    funding("RERC-FND-USDA-023", "Emergency Community Water Assistance Grants", USDA, "Open when checked", NATIONAL,
            "Rural public bodies; nonprofits; federally recognized Tribes", "Implementation",
            "drinking water; emergency response; drought; disaster recovery", "Grant", "Varies by emergency and project", "No match stated",
            "Applications are accepted on an ongoing basis from October 1 through September 30.",
            "Helps rural communities prepare for or recover from emergencies that threaten safe drinking water.",
            "https://www.rd.usda.gov/programs-services/water-environmental-programs/emergency-community-water-assistance-grants"),
    funding("RERC-FND-USDA-024", "Grants for Rural and Native Alaskan Villages", USDA, "Open when checked", "Alaska",
            "Eligible rural Alaska villages and the State of Alaska for eligible villages or hubs", "Construction",
            "drinking water; wastewater; Alaska Native villages; sanitation", "Grant", "Up to 75% of eligible project cost", "At least 25% state or local contribution",
            "Applications are accepted year-round through the Alaska Rural Development office.",
            "Funds drinking water and waste disposal systems that address severe sanitation needs in remote Alaska villages.",
            "https://www.rd.usda.gov/programs-services/water-environmental-programs/grants-rural-and-native-alaskan-villages"),
    funding("RERC-FND-USDA-025", "Revolving Funds for Financing Water and Wastewater Projects", USDA, "Cycle closed", NATIONAL,
            "Qualified nonprofits with authority and capacity to operate a revolving loan fund", "Mixed",
            "water; wastewater; revolving loan fund; predevelopment", "Grant to capitalize a revolving loan fund", "Subloans up to $200,000", "At least 20%",
            "The FY2026 application window closed July 3, 2026; monitor the official page for the next cycle.",
            "Helps qualified nonprofits provide small loans for rural water and wastewater predevelopment and capital projects.",
            "https://www.rd.usda.gov/programs-services/water-environmental-programs/revolving-funds-financing-water-and-wastewater-projects"),
    funding("RERC-FND-USDA-026", "Rural Decentralized Water Systems Grant Program", USDA, "Cycle closed", NATIONAL,
            "Qualified nonprofits, including tribally owned nonprofits", "Mixed",
            "household wells; septic systems; revolving loan fund; rural housing", "Grant", "Varies by NOFO; household subloans may be up to $15,000", "At least 10%",
            "Applications were not being accepted when checked; monitor Grants.gov and the official program page.",
            "Helps nonprofits finance household wells and decentralized wastewater systems in eligible rural areas.",
            "https://www.rd.usda.gov/programs-services/water-environmental-programs/rural-decentralized-water-systems-grant-program"),
    funding("RERC-FND-USDA-027", "SEARCH Grants for Rural Communities and Households", USDA, "Open when checked", NATIONAL,
            "Governments; nonprofits; federally recognized Tribes serving very small, financially distressed rural communities", "Planning",
            "water; wastewater; feasibility; engineering; technical assistance", "Grant", "Up to $30,000 in program guidance", "No match stated",
            "Applications are accepted year-round through local Rural Development offices.",
            "Pays for feasibility studies, design, and technical assistance for water and waste projects in very small rural communities.",
            "https://www.rd.usda.gov/programs-services/water-environmental-programs/search-special-evaluation-assistance-rural-communities-and-households"),
    funding("RERC-FND-USDA-028", "Solid Waste Management Grants", USDA, "Recurring", NATIONAL,
            "Qualified public or private nonprofits providing solid-waste technical assistance or training", "Planning",
            "solid waste; water quality; technical assistance; training", "Grant", "Varies by annual NOFO", "No match stated",
            "Annual competitive cycle; monitor the official page for the next deadline.",
            "Funds technical assistance and training that improve rural solid-waste planning and management.",
            "https://www.rd.usda.gov/programs-services/water-environmental-programs/solid-waste-management-grants"),
    funding("RERC-FND-USDA-029", "Innovative Regional Wastewater Treatment Solutions Grant Pilot", USDA, "Cycle closed", NATIONAL,
            "Eligible regional consortia that include or coordinate with a regional university", "Mixed",
            "wastewater; innovation; persistent poverty; technical assistance; construction", "Grant", "Varies by NOFO", "No match stated",
            "The published application window is closed; monitor the official page for any new round.",
            "Supports study, design, and construction of regional wastewater solutions for historically impoverished rural communities.",
            "https://www.rd.usda.gov/programs-services/water-environmental-programs/technical-assistance-and-construction-innovative-regional-wastewater-treatment-solutions-tac-rwts"),
    funding("RERC-FND-USDA-030", "Water and Waste Facility Loans and Grants for Tribal Lands", USDA, "Open when checked", NATIONAL,
            "Federally recognized Tribes; eligible governments and nonprofits serving qualifying Tribal areas", "Construction",
            "Tribal communities; drinking water; wastewater; health", "Loan and grant", "Varies by project and need", "Usually required; some projects may receive full grant funding",
            "Applications are accepted on an ongoing basis from October 1 through September 30.",
            "Funds basic drinking water, waste disposal, and stormwater systems where inadequate service creates serious health risks.",
            "https://www.rd.usda.gov/programs-services/water-environmental-programs/water-and-waste-facility-loans-and-grants-alleviate-health-risks-tribal-lands"),
    funding("RERC-FND-USDA-031", "Water and Waste Disposal Loans and Grants", USDA, "Open when checked", NATIONAL,
            "State and local governments; private nonprofits; federally recognized Tribes serving eligible rural areas", "Mixed",
            "drinking water; wastewater; solid waste; stormwater; infrastructure", "Loan and grant", "Varies by project; long-term low-interest financing", "Varies",
            "Applications are accepted on an ongoing basis from October 1 through September 30.",
            "Finances drinking water, sewer, solid-waste, and stormwater infrastructure in eligible rural communities.",
            "https://www.rd.usda.gov/programs-services/water-environmental-programs/water-waste-disposal-loan-grant-program"),
    funding("RERC-FND-USDA-032", "Water and Waste Disposal Loan Guarantees", USDA, "Open when checked", NATIONAL,
            "Approved lenders financing eligible rural water and waste borrowers", "Construction",
            "drinking water; wastewater; solid waste; stormwater; infrastructure", "Loan guarantee", "Varies by approved loan", "Borrower and lender terms apply",
            "Applications are accepted from eligible lenders; confirm current availability with USDA.",
            "Helps lenders provide affordable financing for rural water and waste disposal systems.",
            "https://www.rd.usda.gov/programs-services/water-environmental-programs/water-waste-disposal-loan-guarantees"),
    funding("RERC-FND-USDA-033", "Water and Waste Disposal Predevelopment Planning Grants", USDA, "Open when checked", NATIONAL,
            "State and local governments; nonprofits; federally recognized Tribes serving eligible low-income rural communities", "Planning",
            "water; wastewater; planning; engineering; applications", "Grant", "Varies by project", "At least 25% in program guidance",
            "Applications are accepted year-round through local Rural Development offices.",
            "Helps eligible low-income communities prepare plans and applications for rural water and waste projects.",
            "https://www.rd.usda.gov/programs-services/water-environmental-programs/water-waste-disposal-predevelopment-planning-grants"),
    funding("RERC-FND-USDA-034", "Water and Waste Disposal Technical Assistance and Training Grants", USDA, "Recurring", NATIONAL,
            "Qualified nonprofits with experience providing water and waste technical assistance or training", "Planning",
            "water; wastewater; technical assistance; training; operations", "Grant", "Varies by annual NOFO", "Applicant contributions are used first",
            "The annual application window is October 1 through December 31.",
            "Funds technical assistance, training, application help, and operational support for rural water and waste systems.",
            "https://www.rd.usda.gov/programs-services/water-environmental-programs/water-waste-disposal-technical-assistance-training-grants"),
    funding("RERC-FND-USDA-035", "Rural Economic Development Loan and Grant Program", USDA, "Recurring", NATIONAL,
            "Current or former Rural Utilities Service borrowers and eligible nonprofit utilities", "Mixed",
            "economic development; revolving loan fund; business; community facilities", "Loan and grant", "Varies by quarterly competition", "Program terms apply",
            "Quarterly competitions; the last listed FY2026 deadline was June 30, 2026. Monitor the official page for FY2027 dates.",
            "Provides zero-interest loans and grants that utilities use to finance rural business and community projects.",
            "https://www.rd.usda.gov/programs-services/business-programs/rural-economic-development-loan-grant-programs"),
    funding("RERC-FND-USDA-036", "Rural Energy for America Program", USDA, "Partly open", NATIONAL,
            "Agricultural producers; rural small businesses; approved lenders", "Implementation",
            "renewable energy; energy efficiency; agriculture; small business", "Grant and guaranteed loan", "Varies by project and funding type", "Varies",
            "Grant applications were closed when checked; guaranteed loan applications may be submitted.",
            "Supports renewable-energy systems and energy-efficiency improvements for rural small businesses and agricultural producers.",
            "https://www.rd.usda.gov/programs-services/energy-programs/rural-energy-america-program-renewable-energy-systems-energy-efficiency-improvement-guaranteed-loans"),
    funding("RERC-FND-USDA-037", "Rural Business Development Grants", USDA, "Cycle closed", NATIONAL,
            "Public bodies; federally recognized Tribes; nonprofits serving rural areas", "Mixed",
            "business development; jobs; planning; technical assistance", "Grant", "No fixed maximum; smaller requests receive priority", "No match stated",
            "The FY2026 deadlines were June 15 and June 30, 2026; monitor the program page for the next cycle.",
            "Funds rural business planning, technical assistance, training, and projects that support job creation.",
            "https://www.rd.usda.gov/programs-services/business-programs/rural-business-development-grants"),
    funding("RERC-FND-USDA-038", "Rural Microentrepreneur Assistance Program", USDA, "Recurring", NATIONAL,
            "Microenterprise development organizations and approved microlenders serving rural businesses", "Mixed",
            "small business; entrepreneurship; microloans; technical assistance", "Loan and grant", "Varies by quarterly competition", "Program terms apply",
            "Quarterly competitions; the last listed FY2026 deadline was June 30, 2026. Monitor the official page for FY2027 dates.",
            "Helps rural microenterprise organizations provide loans, training, and technical assistance to small businesses.",
            "https://www.rd.usda.gov/programs-services/business-programs/rural-microentrepreneur-assistance-program"),
    funding("RERC-FND-USDA-039", "Rural Health and Safety Education Competitive Grants", "USDA National Institute of Food and Agriculture", "Cycle closed", NATIONAL,
            "Eligible 1862, 1890, and 1994 land-grant institutions", "Implementation",
            "rural health; safety; education; extension", "Grant", "$350,000 per FY2026 award", "No match required",
            "The FY2026 application deadline was June 23, 2026; monitor the official page for the next cycle.",
            "Funds education programs that improve health, safety, and quality of life in rural communities.",
            "https://www.nifa.usda.gov/grants/funding-opportunities/rural-health-safety-education-competitive-grants-program"),
    funding("RERC-FND-USDA-040", "Timber Production Expansion Guaranteed Loan Program", USDA, "Open when checked", NATIONAL,
            "Approved lenders financing eligible sawmills and wood-processing businesses", "Construction",
            "forest products; timber; manufacturing; jobs; wildfire risk", "Loan guarantee", "Loans up to $25 million; 90% guarantee", "Borrower and lender terms apply",
            "Applications are accepted through approved lenders while program funds remain available.",
            "Supports sawmills and wood-processing facilities that use restoration byproducts from National Forest System lands.",
            "https://www.rd.usda.gov/timber-production-expansion-guaranteed-loan-program-tpep"),
    funding("RERC-FND-FRA-2026-001", "Consolidated Rail Infrastructure and Safety Improvements Program", "Federal Railroad Administration", "Cycle closed", "United States",
            "States; local governments; Tribes; rail carriers; ports; universities; other eligible rail partners", "Mixed",
            "rail; transportation; safety; multimodal connections; infrastructure", "Grant", "About $2.04 billion available in the FY2025-2026 round", "Varies by project",
            "The FY2025-2026 deadline was June 25, 2026; monitor the program page for the next round.",
            "Funds rail safety, reliability, capacity, grade crossings, regional planning, and multimodal connections.",
            "https://railroads.dot.gov/grants-loans/consolidated-rail-infrastructure-and-safety-improvements-crisi-program"),
    funding("RERC-FND-DOE-2026-001", "Unleashing Tribal Energy Development", "U.S. Department of Energy Office of Indian Energy", "Cycle closed", NATIONAL,
            "Indian Tribes; Alaska Native corporations; Tribal organizations; Tribal energy organizations; Tribal colleges and universities", "Mixed",
            "Tribal energy; infrastructure; planning; economic development", "Grant and cooperative agreement", "$50 million total FY2026 opportunity", "0% or 10% depending on project type",
            "The FY2026 application deadline was July 24, 2026; monitor the Office of Indian Energy for future opportunities.",
            "Supports affordable, reliable, and secure Tribal energy planning and project development.",
            "https://www.energy.gov/indianenergy/articles/50-million-available-advance-affordable-reliable-and-secure-energy-tribes"),
    funding("RERC-FND-USDA-041", "Value-Added Producer Grants", USDA, "Cycle closed", NATIONAL,
            "Independent agricultural producers; producer groups; farmer or rancher cooperatives; eligible majority-controlled producer businesses", "Mixed",
            "agriculture; local food; tourism; business planning; marketing", "Grant", "Varies by planning or working-capital request", "Matching funds required",
            "The FY2026 application deadline was April 22, 2026; monitor the official page for the next cycle.",
            "Funds planning and working capital that help agricultural producers develop and market value-added products.",
            "https://www.rd.usda.gov/programs-services/business-programs/value-added-producer-grants"),
    funding("RERC-FND-WA-2026-001", "Drinking Water State Revolving Fund Programs", "Washington State Department of Health", "Recurring", "Washington",
            "Eligible public and nonprofit water systems; some programs also serve local health jurisdictions and community organizations", "Mixed",
            "drinking water; planning; construction; lead service lines; emergency response", "Loan and grant", "Varies by DWSRF subprogram", "Varies",
            "Application windows vary; source-water protection and emergency assistance are ongoing when funds are available.",
            "Provides planning, consolidation, lead-service-line, construction, and emergency financing for Washington drinking-water systems.",
            "https://doh.wa.gov/community-and-environment/drinking-water/water-system-assistance/drinking-water-state-revolving-fund-dwsrf"),
    funding("RERC-FND-WA-2026-002", "Source Water Protection Local Assistance Program", "Washington State Department of Health", "Open when checked", "Washington",
            "Water systems; local governments; Tribes; conservation districts; nonprofits; educational institutions working with eligible systems", "Mixed",
            "drinking water; source protection; watershed health; planning", "Grant", "Up to $250,000 per project; some applicants may be limited to $40,000", "No match stated",
            "Applications are accepted year-round until available funding is spent.",
            "Funds projects that protect drinking-water sources, improve watershed health, and reduce contamination risks.",
            "https://doh.wa.gov/community-and-environment/drinking-water/source-water/local-assistance-grant-program"),
    funding("RERC-FND-WA-2026-003", "Water Quality Combined Funding Program", "Washington State Department of Ecology", "Upcoming cycle", "Washington",
            "Counties; cities; towns; Tribes; special districts; conservation districts; eligible nonprofits", "Mixed",
            "water quality; wastewater; stormwater; nonpoint pollution; onsite sewage", "Grant and loan", "$100 million to $200 million available in a typical annual cycle", "Up to 25% depending on source",
            "State fiscal year 2028 applications are scheduled for August 11 through September 30, 2026, at 5 p.m.",
            "Uses one application for several state and federal water-quality grant and loan programs.",
            "https://ecology.wa.gov/about-us/payments-contracts-grants/grants-loans/find-a-grant-or-loan/water-quality-combined"),
    funding("RERC-FND-WA-2026-004", "CERB Planning Program", "Washington Community Economic Revitalization Board", "Open when checked", "Washington",
            "Cities; towns; counties; Tribes; municipal and quasi-municipal corporations; ports; special districts", "Planning",
            "economic development; feasibility; site planning; rural broadband", "Grant", "Up to $100,000 depending on project tier", "At least 20% cash match",
            "Applications are considered on an ongoing basis; contact CERB staff before applying.",
            "Funds studies and planning for high-priority economic development, site-readiness, and rural broadband projects.",
            "https://www.commerce.wa.gov/cerb/cerb-pp/"),
    funding("RERC-FND-WA-2026-005", "Public Works Board Traditional Financing", "Washington State Public Works Board", "Recurring", "Washington",
            "Eligible local governments and special purpose districts", "Mixed",
            "public works; infrastructure; planning; preconstruction; construction; emergency", "Loan and grant", "Varies by funding cycle; up to $20 million noted for FY2027 preconstruction", "Varies",
            "Preconstruction and construction cycles vary; emergency assistance may be available when qualifying events occur.",
            "Provides financing for planning, preconstruction, construction, and emergency public-works projects.",
            "https://www.commerce.wa.gov/pwb/pwb-financing/"),
    funding("RERC-FND-RCAC-2026-001", "Environmental Infrastructure Loans", "Rural Community Assistance Corporation", "Open when checked", "Multi-State",
            "Nonprofits; public agencies; Tribal governments in the rural West", "Mixed",
            "water; wastewater; solid waste; stormwater; feasibility; construction", "Loan", "Varies by feasibility, predevelopment, construction, or intermediate-term product", "Repayment required",
            "Applications are accepted on an ongoing basis, subject to available funds.",
            "Offers feasibility, predevelopment, construction, and intermediate-term loans for rural water and waste projects.",
            "https://www.rcac.org/lending/environmental-loans/"),
    funding("RERC-FND-WA-2026-006", "Energy Grants and Incentives for Public Buildings", "Washington State Department of Commerce", "Recurring", "Washington",
            "Eligible public entities, local governments, Tribes, schools, colleges, and other public-facility owners", "Implementation",
            "energy efficiency; solar; resilience; public buildings", "Grant and incentive", "Varies by program and solicitation", "Varies",
            "Cycles vary for energy-efficiency, solar, storage, and block-grant programs; review current solicitations.",
            "Collects funding opportunities for energy efficiency, solar, resilience, and related public-building improvements.",
            "https://www.commerce.wa.gov/energy-incentives/"),
    funding("RERC-FND-NRWA-2026-001", "Rural Water Loan Fund", "National Rural Water Association", "Open when checked", "United States",
            "Public water and wastewater systems, Tribes, nonprofits, cooperatives, counties, and special districts serving small or rural communities", "Mixed",
            "water; wastewater; emergency repair; predevelopment; equipment", "Loan", "Up to $200,000 or 75% of project cost", "At least 25% of project cost",
            "Applications are accepted on an ongoing basis; emergency loans have expedited review.",
            "Provides low-cost loans for small water and wastewater projects, predevelopment, repairs, and emergencies.",
            "https://nrwa.org/members/products-services-portfolio/rural-water-loan-fund/"),
    funding("RERC-FND-WA-2026-007", "Connecting Housing to Infrastructure Program", "Washington State Department of Commerce", "Open when checked", "Washington",
            "Cities; counties; public utility districts partnering with affordable-housing developers", "Construction",
            "housing; water; sewer; stormwater; infrastructure", "Grant", "Up to $2 million", "Program conditions apply",
            "Applications are due September 30, 2026.",
            "Pays for utility connections and infrastructure needed to bring eligible affordable housing projects online.",
            "https://www.commerce.wa.gov/funding/apply-now-connecting-housing-to-infrastructure-program-chip-accepting-applications-for-up-to-31-million-in-grant-funding/"),
    funding("RERC-FND-WA-2026-008", "Hazard Mitigation Grant Program", "Washington Emergency Management Division and FEMA", "Disaster-triggered", "Washington",
            "Eligible state, local, and Tribal governments; qualifying projects are submitted through the state", "Planning",
            "hazard mitigation; resilience; disaster recovery; infrastructure", "Grant", "Varies by disaster declaration", "Typically 25% nonfederal share",
            "Becomes available after eligible presidential disaster declarations; state notices set project deadlines.",
            "Funds plans and cost-effective projects that reduce future disaster damage.",
            "https://mil.wa.gov/recovery"),
    funding("RERC-FND-WA-2026-009", "FEMA Public Assistance Program", "Washington Emergency Management Division and FEMA", "Disaster-triggered", "Washington",
            "Eligible state, local, and Tribal governments; certain private nonprofits", "Implementation",
            "disaster recovery; debris removal; emergency work; public infrastructure", "Grant", "Varies by declared disaster and eligible costs", "Typically 25% nonfederal share",
            "Available after eligible presidential disaster declarations; incident-specific deadlines apply.",
            "Helps eligible communities remove debris, perform emergency work, and repair disaster-damaged public facilities.",
            "https://mil.wa.gov/recovery"),
    funding("RERC-FND-WA-2026-010", "Emergency Rapid Response Grants Program", "Washington State Department of Commerce", "Open when checked", "Washington",
            "Local and Tribal governments responding to declared emergencies or disasters", "Implementation",
            "emergency response; essential services; utilities; transportation; shelter", "Grant", "$3 million available per state fiscal year", "No match stated",
            "Requests are considered on an ongoing basis until annual funds are exhausted.",
            "Restores essential community services and lifelines after declared emergencies or disasters.",
            "https://www.commerce.wa.gov/err/"),
    resource("RERC-RES-USDA-2026-001", "Targeted Technical Assistance for Rural Hospitals", "Health Resources and Services Administration", "Technical assistance",
             "Provides targeted technical help to rural hospitals working on financial, operational, and quality-improvement needs.",
             "https://www.hrsa.gov/rural-health/grants/rural-hospitals/ttap"),
    resource("RERC-RES-USDA-2026-002", "USDA Rural Development Tribal Relations", USDA, "Program directory and contacts",
             "Connects Tribal communities with Rural Development programs, contacts, and information organized for Tribal needs.",
             "https://www.rd.usda.gov/about-rd/tribal-relations"),
    resource("RERC-RES-USDA-2026-003", "Rural Development Rural Philanthropy Project", USDA, "Research report",
             "Explains how rural philanthropy can support local capacity, partnerships, and long-term community investment.",
             "https://www.rd.usda.gov/media/file/download/usda-rd-rural-philanthropy-report-03122026.pdf"),
    resource("RERC-RES-USDA-2026-004", "Rural Philanthropy Project StoryMap", USDA, "Interactive map and examples",
             "Maps rural philanthropy examples and helps communities explore partnership approaches in different places.",
             "https://storymaps.arcgis.com/stories/d498f6bbff054f26b1d94d556832bd27"),
    resource("RERC-RES-USDA-2026-005", "Rural Data Gateway Lender Lens", USDA, "Data tool",
             "Lets users explore USDA guaranteed-loan activity and participating lenders by program and geography.",
             "https://www.rd.usda.gov/rural-data-gateway/onerd-investments"),
    resource("RERC-RES-USDA-2026-006", "USDA Income and Property Eligibility Site", USDA, "Eligibility tool",
             "Checks whether a location and household income may meet geographic and income rules for selected USDA programs.",
             "https://eligibility.sc.egov.usda.gov/eligibility/welcomeAction.do"),
    resource("RERC-RES-USDA-2026-007", "USDA Rural Development Eligibility Lookup Tool", USDA, "Interactive eligibility map",
             "Provides a map-based way to review potential Rural Development program eligibility before contacting USDA.",
             "https://experience.arcgis.com/experience/3c2f6c9581bb4f06a4ab68df8f34b0be"),
    resource("RERC-RES-USDA-2026-008", "2026 Rural Rental Housing Preservation Academy", "Enterprise Community Partners", "Training program and materials",
             "Offers training and resources for organizations working to preserve affordable rural rental housing.",
             "https://www.enterprisecommunity.org/learning-center/resources/2026-rural-rental-housing-preservation-academy"),
]

# RCAC serves a reviewed, bounded set of western states and Pacific jurisdictions.
for item in NEW_ITEMS:
    if item["item_id"] == "RERC-FND-RCAC-2026-001":
        item["covered_states"] = [
            "Alaska", "Arizona", "California", "Colorado", "Hawaii", "Idaho", "Montana", "Nevada",
            "New Mexico", "Oregon", "Utah", "Washington", "Wyoming", "American Samoa", "Guam",
            "Northern Mariana Islands",
        ]
        item["coverage_note"] = "RCAC environmental loans serve the rural West and listed Pacific jurisdictions."
        item["coverage_source_url"] = "https://www.rcac.org/lending/environmental-loans/"


NEW_CASE = {
    "item_id": "RERC-CASE-USDA-RD-WISCONSIN-VALUE-ADDED-PRODUCERS-2026",
    "item_type": "Case Study",
    "title": "Wisconsin Agricultural Entrepreneurs Expand with Value-Added Producer Grants",
    "organization": "USDA Rural Development Success Stories",
    "status": "Published case study",
    "last_checked": CHECKED,
    "geography": "Wisconsin",
    "eligible_users": "Communities looking for comparable examples",
    "project_stage": "Implementation",
    "topic_tags": "Value Added; Agriculture; Local Food; Entrepreneurship; Marketing; Tasting Room; Agritourism",
    "support_type": "Case study",
    "amount_or_cost": "",
    "match_or_cost": "",
    "deadline_or_availability": "2026",
    "summary": "Producers in East Troy, Chilton, and Bayfield used Value-Added Producer Grants for business planning, marketing, packaging, distribution, and working capital. The projects expanded rural food and beverage businesses, created jobs, and supported visitor-facing products and tasting-room activity.",
    "why_it_matters": "",
    "source_url": "https://www.rd.usda.gov/newsroom/success-stories/usda-rural-development-grant-helps-wisconsin-agricultural-entrepreneurs-expand-and-grow",
    "case_place": "East Troy, Chilton, and Bayfield",
    "case_state": "Wisconsin",
    "case_place_type": "statewide_or_multi_community",
    "case_program": "USDA Rural Development Success Stories",
    "case_year": "2026",
    "case_partners": "The Hive Taproom; Kidfarm LLC; Hauser's Superior View Farm and Apfelhaus Cidery; USDA Rural Development",
}


def load_assignment(path: Path, prefix: str) -> dict:
    raw = path.read_text(encoding="utf-8").strip()
    if not raw.startswith(prefix) or not raw.endswith(";"):
        raise ValueError(f"Unexpected assignment format: {path}")
    return json.loads(raw[len(prefix):-1])


def write_assignment(path: Path, prefix: str, payload: dict) -> None:
    path.write_text(prefix + json.dumps(payload, ensure_ascii=False, separators=(",", ":")) + ";\n", encoding="utf-8", newline="\n")


def main() -> int:
    catalog = load_assignment(DATA, PREFIX)
    existing_ids = {item["item_id"] for item in catalog["items"]}
    existing_urls = {item["source_url"].rstrip("/").lower() for item in catalog["items"]}
    additions = []
    for item in NEW_ITEMS:
        if item["item_id"] in existing_ids:
            continue
        normalized_url = item["source_url"].rstrip("/").lower()
        if normalized_url in existing_urls:
            raise ValueError(f"Source URL already exists under another ID: {item['source_url']}")
        additions.append(item)
    catalog["items"].extend(additions)
    catalog["updated"] = CHECKED
    catalog["counts"] = {
        "combined": len(catalog["items"]),
        "funding": sum(item["item_type"] == "Funding" for item in catalog["items"]),
        "resources": sum(item["item_type"] == "Resource" for item in catalog["items"]),
    }
    write_assignment(DATA, PREFIX, catalog)
    export_catalog(catalog)

    cases = load_assignment(CASES, CASE_PREFIX)
    if NEW_CASE["item_id"] not in {item["item_id"] for item in cases["items"]}:
        cases["items"].append(NEW_CASE)
    cases["generated_at"] = CHECKED
    cases["count"] = len(cases["items"])
    write_assignment(CASES, CASE_PREFIX, cases)

    result = {
        "status": "PASS",
        "catalog_added": len(additions),
        "catalog_counts": catalog["counts"],
        "case_studies": len(cases["items"]),
    }
    print(json.dumps(result, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
